// <auto-generated />
using System;
using EmailValidation.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace EmailValidation.Migrations.DataContext2Migrations
{
    [DbContext(typeof(DataContext2))]
    [Migration("20210524235005_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("EmailValidation.Models.EmailV2", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<bool>("Catch_All")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("Created_At")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("Deliverable")
                        .HasColumnType("boolean");

                    b.Property<bool>("Disposable")
                        .HasColumnType("boolean");

                    b.Property<string>("Domain")
                        .HasColumnType("text");

                    b.Property<string>("Email_Address")
                        .HasColumnType("text");

                    b.Property<bool>("Gibberish")
                        .HasColumnType("boolean");

                    b.Property<bool>("Spam")
                        .HasColumnType("boolean");

                    b.Property<bool>("Valid_Syntax")
                        .HasColumnType("boolean");

                    b.Property<bool>("WebMail")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("EmailsV2");
                });
#pragma warning restore 612, 618
        }
    }
}
